// import React from "react";

// export default function PrivacyPage() {
//   return (
//     <div className="min-h-screen bg-white">
//       <div className=" mx-auto px-6 py-12">
//         <div className="text-center mb-8">
//           <span className="text-red-500 font-semibold uppercase tracking-widest text-xs">
//             Privacy Policy
//           </span>
//           <h1 className="text-3xl md:text-4xl font-bold mt-3 mb-1">
//             Privacy Policy
//           </h1>
//           <p className="text-sm text-gray-500">Last updated: January 1, 2025</p>
//         </div>

//         <p className="text-gray-600 mb-6 max-w-7xl mx-auto">
//           Your privacy is important to us. This policy explains what data we
//           collect, how we use it, and your rights as a user of RentHub.
//         </p>

//         <ol className="space-y-6 list-decimal list-inside text-gray-700 max-w-7xl mx-auto">
//           <li>
//             <h3 className="font-semibold inline text-black ">
//               Information We Collect
//             </h3>
//             <p className="text-sm text-gray-600 mt-2">
//               We collect information you provide directly (name, email, phone,
//               payment details) and data generated by your use of the platform
//               (search history, booking activity, device info).
//             </p>
//           </li>

//           <li>
//             <h3 className="font-semibold inline text-black  ">
//               How We Use Your Data
//             </h3>
//             <div className="text-sm text-gray-600 mt-2">
//               <p className="mb-3">Your data is used to:</p>
//               <ul className="pl-4 space-y-2">
//                 <li className="flex items-start">
//                   <span
//                     className="w-2 h-2 bg-red-500 inline-block mr-3 mt-2 rounded-sm"
//                     aria-hidden="true"
//                   />
//                   <span>Process and manage bookings</span>
//                 </li>
//                 <li className="flex items-start">
//                   <span
//                     className="w-2 h-2 bg-red-500 inline-block mr-3 mt-2 rounded-sm"
//                     aria-hidden="true"
//                   />
//                   <span>Send booking confirmations and reminders</span>
//                 </li>
//                 <li className="flex items-start">
//                   <span
//                     className="w-2 h-2 bg-red-500 inline-block mr-3 mt-2 rounded-sm"
//                     aria-hidden="true"
//                   />
//                   <span>Improve platform features and performance</span>
//                 </li>
//                 <li className="flex items-start">
//                   <span
//                     className="w-2 h-2 bg-red-500 inline-block mr-3 mt-2 rounded-sm"
//                     aria-hidden="true"
//                   />
//                   <span>Send marketing communications (with your consent)</span>
//                 </li>
//                 <li className="flex items-start">
//                   <span
//                     className="w-2 h-2 bg-red-500 inline-block mr-3 mt-2 rounded-sm"
//                     aria-hidden="true"
//                   />
//                   <span>Comply with legal obligations</span>
//                 </li>
//               </ul>
//             </div>
//           </li>

//           <li>
//             <h3 className="font-semibold inline text-black ">Data Sharing</h3>
//             <div className="text-sm text-gray-600 mt-2">
//               <p className="mb-3">
//                 We do not sell your personal data. We share data only with:
//               </p>
//               <ul className="pl-4 space-y-2">
//                 <li className="flex items-start">
//                   <span
//                     className="w-2 h-2 bg-red-500 inline-block mr-3 mt-2 rounded-sm"
//                     aria-hidden="true"
//                   />
//                   <span>
//                     Payment processors (Stripe) for transaction processing
//                   </span>
//                 </li>
//                 <li className="flex items-start">
//                   <span
//                     className="w-2 h-2 bg-red-500 inline-block mr-3 mt-2 rounded-sm"
//                     aria-hidden="true"
//                   />
//                   <span>
//                     Hosting service providers for platform infrastructure
//                   </span>
//                 </li>
//                 <li className="flex items-start">
//                   <span
//                     className="w-2 h-2 bg-red-500 inline-block mr-3 mt-2 rounded-sm"
//                     aria-hidden="true"
//                   />
//                   <span>Legal authorities when required by law</span>
//                 </li>
//               </ul>
//             </div>
//             <div className="mt-3 p-4 bg-yellow-50 border border-yellow-100 rounded-lg text-sm text-yellow-800">
//               We will never sell your personal information to third-party
//               advertisers.
//             </div>
//           </li>

//           <li>
//             <h3 className="font-semibold inline text-black ">
//               Cookies &amp; Tracking
//             </h3>
//             <p className="text-sm text-gray-600 mt-2">
//               RentHub uses cookies to maintain session state, remember
//               preferences, and analyze usage. You can manage cookie preferences
//               in your browser settings or via our cookie banner.
//             </p>
//           </li>

//           <li>
//             <h3 className="font-semibold inline text-black ">Data Retention</h3>
//             <p className="text-sm text-gray-600 mt-2">
//               We retain your account data for as long as your account is active.
//               Booking records are retained for 5 years for legal and financial
//               compliance.
//             </p>
//           </li>

//           <li>
//             <h3 className="font-semibold inline text-black  ">Your Rights</h3>
//             <div className="text-sm text-gray-600 mt-2">
//               <p className="mb-3">You have the right to:</p>
//               <ul className="pl-4 space-y-2">
//                 <li className="flex items-start">
//                   <span
//                     className="w-2 h-2 bg-red-500 inline-block mr-3 mt-2 rounded-sm"
//                     aria-hidden="true"
//                   />
//                   <span>Access the personal data we hold about you</span>
//                 </li>
//                 <li className="flex items-start">
//                   <span
//                     className="w-2 h-2 bg-red-500 inline-block mr-3 mt-2 rounded-sm"
//                     aria-hidden="true"
//                   />
//                   <span>Request correction of inaccurate data</span>
//                 </li>
//                 <li className="flex items-start">
//                   <span
//                     className="w-2 h-2 bg-red-500 inline-block mr-3 mt-2 rounded-sm"
//                     aria-hidden="true"
//                   />
//                   <span>
//                     Request deletion of your account and associated data
//                   </span>
//                 </li>
//                 <li className="flex items-start">
//                   <span
//                     className="w-2 h-2 bg-red-500 inline-block mr-3 mt-2 rounded-sm"
//                     aria-hidden="true"
//                   />
//                   <span>
//                     Withdraw consent for marketing communications at any time
//                   </span>
//                 </li>
//               </ul>
//             </div>
//           </li>

//           <li>
//             <h3 className="font-semibold inline text-black ">
//               Third-Party Services
//             </h3>
//             <p className="text-sm text-gray-600 mt-2">
//               Our platform uses third-party services (payments, maps, chat).
//               These services have their own privacy policies which we encourage
//               you to review.
//             </p>
//           </li>

//           <li>
//             <h3 className="font-semibold inline text-black ">
//               Children&apos;s Privacy
//             </h3>
//             <p className="text-sm text-gray-600 mt-2">
//               RentHub is not directed at children under 18. We do not knowingly
//               collect data from minors.
//             </p>
//           </li>

//           <li>
//             <h3 className="font-semibold inline text-black ">Security</h3>
//             <p className="text-sm text-gray-600 mt-2">
//               We use industry-standard encryption (SSL/TLS) to protect data in
//               transit. Passwords are hashed and never stored in plain text.
//             </p>
//           </li>

//           <li>
//             <h3 className="font-semibold inline text-black ">
//               Changes to This Policy
//             </h3>
//             <p className="text-sm text-gray-600 mt-2">
//               We may update this policy periodically. We will notify registered
//               users of significant changes by email.
//             </p>
//           </li>

//           <li>
//             <h3 className="font-semibold inline text-black ">Contact Us</h3>
//             <p className="text-sm text-gray-600 mt-2">
//               For privacy-related requests, contact us at: privacy@renthub.com
//             </p>
//           </li>
//         </ol>
//       </div>
//     </div>
//   );
// }

"use client";

import React from "react";
import { useTranslations, useLocale } from "next-intl";

export default function PrivacyPage() {
  const t = useTranslations("Privacy");
  const locale = useLocale();
  const isRtl = locale === "ar";

  // Helper function to render those specific red-square bullet lists
  const renderRedBulletList = (listKey: string) => {
    const list = t.raw(listKey) as string[];
    return (
      <ul className="ps-4 space-y-2 mt-2">
        {list.map((item, idx) => (
          <li key={idx} className="flex items-start">
            <span
              className={`w-2 h-2 bg-red-500 inline-block mt-2 rounded-sm ${
                isRtl ? "ml-3" : "mr-3"
              }`}
              aria-hidden="true"
            />
            <span>{item}</span>
          </li>
        ))}
      </ul>
    );
  };

  return (
    <div className="min-h-screen bg-white" dir={isRtl ? "rtl" : "ltr"}>
      <div className="mx-auto px-6 py-12">
        {/* Header */}
        <div className="text-center mb-8">
          <span className="text-red-500 font-semibold uppercase tracking-widest text-xs">
            {t("badge")}
          </span>
          <h1 className="text-3xl md:text-4xl font-bold mt-3 mb-1">
            {t("title")}
          </h1>
          <p className="text-sm text-gray-500">{t("updated")}</p>
        </div>

        <p className="text-gray-600 mb-6 max-w-7xl mx-auto">{t("intro")}</p>

        <ol className="space-y-6 list-decimal list-inside text-gray-700 max-w-7xl mx-auto">
          {/* Section 1 */}
          <li>
            <h3 className="font-semibold inline text-black">
              {t("sections.s1.title")}
            </h3>
            <p className="text-sm text-gray-600 mt-2">
              {t("sections.s1.content")}
            </p>
          </li>

          {/* Section 2 */}
          <li>
            <h3 className="font-semibold inline text-black">
              {t("sections.s2.title")}
            </h3>
            <div className="text-sm text-gray-600 mt-2">
              <p className="mb-3">{t("sections.s2.content")}</p>
              {renderRedBulletList("sections.s2.list")}
            </div>
          </li>

          {/* Section 3 */}
          <li>
            <h3 className="font-semibold inline text-black">
              {t("sections.s3.title")}
            </h3>
            <div className="text-sm text-gray-600 mt-2">
              <p className="mb-3">{t("sections.s3.content")}</p>
              {renderRedBulletList("sections.s3.list")}
            </div>
            <div className="mt-3 p-4 bg-yellow-50 border border-yellow-100 rounded-lg text-sm text-yellow-800">
              {t("sections.s3.note")}
            </div>
          </li>

          {/* Section 4 */}
          <li>
            <h3 className="font-semibold inline text-black">
              {t("sections.s4.title")}
            </h3>
            <p className="text-sm text-gray-600 mt-2">
              {t("sections.s4.content")}
            </p>
          </li>

          {/* Section 5 */}
          <li>
            <h3 className="font-semibold inline text-black">
              {t("sections.s5.title")}
            </h3>
            <p className="text-sm text-gray-600 mt-2">
              {t("sections.s5.content")}
            </p>
          </li>

          {/* Section 6 */}
          <li>
            <h3 className="font-semibold inline text-black">
              {t("sections.s6.title")}
            </h3>
            <div className="text-sm text-gray-600 mt-2">
              <p className="mb-3">{t("sections.s6.content")}</p>
              {renderRedBulletList("sections.s6.list")}
            </div>
          </li>

          {/* Section 7 */}
          <li>
            <h3 className="font-semibold inline text-black">
              {t("sections.s7.title")}
            </h3>
            <p className="text-sm text-gray-600 mt-2">
              {t("sections.s7.content")}
            </p>
          </li>

          {/* Section 8 */}
          <li>
            <h3 className="font-semibold inline text-black">
              {t("sections.s8.title")}
            </h3>
            <p className="text-sm text-gray-600 mt-2">
              {t("sections.s8.content")}
            </p>
          </li>

          {/* Section 9 */}
          <li>
            <h3 className="font-semibold inline text-black">
              {t("sections.s9.title")}
            </h3>
            <p className="text-sm text-gray-600 mt-2">
              {t("sections.s9.content")}
            </p>
          </li>

          {/* Section 10 */}
          <li>
            <h3 className="font-semibold inline text-black">
              {t("sections.s10.title")}
            </h3>
            <p className="text-sm text-gray-600 mt-2">
              {t("sections.s10.content")}
            </p>
          </li>

          {/* Section 11 */}
          <li>
            <h3 className="font-semibold inline text-black">
              {t("sections.s11.title")}
            </h3>
            <p className="text-sm text-gray-600 mt-2">
              {t("sections.s11.content")}
            </p>
          </li>
        </ol>
      </div>
    </div>
  );
}
